### ISSUE TITLE
Guide for Gitlab CI

### ISSUE THREAD

**Issue by AVapps** [aedm/minimeteor#8]
Hi,
I've seen that you use Gitlab CI. Could you please provide a guide on how to use minimeteor with it?
Thanks !

**Comment by aedm** [comment]
Hey! Sorry for the late answer.
Here's an example `.gitlab-ci.yml`: https://gitlab.com/aedm/got7-death-pool/blob/master/.gitlab-ci.yml

Basically, the relevant part:

```
build_docker_image:
  image: gitlab/dind:latest
  stage: build
  script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - curl https://aedm.github.io/minimeteor/build.sh | sh -s registry.gitlab.com/aedm/got7-death-pool:$CI_BUILD_REF registry.gitlab.com/aedm/got7-death-pool:latest
  - docker push registry.gitlab.com/aedm/got7-death-pool:$CI_BUILD_REF
  - docker push registry.gitlab.com/aedm/got7-death-pool:latest
  only:
  - release
```

This builds the Docker image and pushes it to GitLab's registry.
