### ISSUE TITLE
Can this be used with docker compose?

### ISSUE THREAD

**Issue by JulianKingman** [aedm/minimeteor#9]
One thing I love about docker is setting things up with compose files. It's very reusable and makes spinning up new apps a no-brainer. Here's an example:
````
fantasysuite-app-meteor:
  environment:
    BUNDLE_URL: fileURL.com/file.zip
    MAIL_URL: [emali url goes here]
    MONGO_URL: [mongo url or link goes here]
    ROOT_URL: https://example.com
  labels:
  image: aedm/minimeteor
````
Can that be done with minimeteor?
